sudo: required
language: python
os: linux
dist: trusty
python:
  - "2.7"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - sudo apt-get -qq install git xvfb wget xz-utils tor
  - easy_install .
  - wget https://archive.torproject.org/tor-package-archive/torbrowser/4.5.1/tor-browser-linux64-4.5.1_en-US.tar.xz
  - tar -xvf tor-browser-linux64-4.5.1_en-US.tar.xz
before_script:
  - cd tbselenium/test
  - export TBB_PATH=../../tor-browser_en-US
script:  py.test
